name: eslint
run-name: eslint check
on: 
  pull_request:
    branches:
      - main
      - dev
jobs: 
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: "./frontend/.nvmrc"
      - run: npm ci
      - run: npm run lint

